name: pocket_doc
description: AI-Powered Health Companion
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.18.1
  google_sign_in: ^6.1.7
  http: ^1.1.2
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true